"""Add concessao_data column to INC

Revision ID: f64db9f5214d
Revises: 
Create Date: 2025-03-21 11:08:28.280252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64db9f5214d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concessao_data', sa.Text(), nullable=True))
        batch_op.alter_column('data',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('representante_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('representante_nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('fornecedor',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('item',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('urgencia',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('urgencia',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('item',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('fornecedor',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('representante_nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('representante_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('data',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('concessao_data')

    # ### end Alembic commands ###
